name: model-training
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - run: pip install -r requirements.txt
        name: Install requirements

      - run: .src/train.py
        name: Train model

      - uses: actions/upload-artifact@v2
        with:
          name: ModelPickle
          path: data/models/model.pickle
